### ISSUE TITLE
Summarizing the curation states for definition and schema:image fields

### ISSUE THREAD

**Issue by ddooley** [FoodOntology/foodon-wikipedia#1]
The script uses wikipedia API to lookup initial sentences for a given term rdfs:label , as well as any appropriately sized image for the food.  Input is a data.tsv table. For items that it looks up, we need the following curation statuses, most of which are manual but a few of which the script takes charge of changing. These apply separately to definition and image columns:

0: item needs to be looked up from wikipedia api

The following statuses all cause the script to ignore the item lookup. status 2,3,4,5 are all manually set.

1: unable to find an exact match at wikipedia.  The script could sets this from status:0 if it is unable to find a match.  This prevents it from being run again on the same item.
2: ignore this item (it may be blank because there is no match via Wikipedia API. This is manually set.
3: item content was fetched from wikipedia, and is awaiting review.
4: manual review of item is occurring.
5: item is ready for release.

**Comment by Anoosha-Sehar** [comment]
Damion, I would like to ask about status 1 & 2.  I was wondering that aren't they both representing the same state? Script will set `status=1` if its not able to find a match at Wikipedia, and I think `status=2` is doing same thing, if I understood it right?  In that case, would it be helpful to change it again to 2 even manually? Or do you mean by difference between exact and closest match?

**Comment by ddooley** [comment]
Basically the script only pays attention to items having status 0, and switches it to 1 (not found) or 3: found and awaiting review.
Status 2 is manually set by a human - probably need to give it a better state name. Case could be called "skip lookup: requires manual review".  Then a human would flip this to state 4 once they had begun addition or review of terms content.

Hope that helps?

**Comment by Anoosha-Sehar** [comment]
Okay thanks, it was helpful to know. I will update both the definition and image status accordingly.
Just another quick question about the already fetched definitions in our input data file, are those ready for release (so I can revise their `status=5 ` in data file)?  or are they still under manual review `status=4`?

**Comment by ddooley** [comment]
the script, if it successfully finds a definition, will update status to 3.  Only humans revise status to 4 or 5 since that's a manual review process.
